apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: bak2gs
spec:
  schedule: "30 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - env:
              - name: MYSQL_HOST
                value: mysql
              - name: BAK_BUCKET
                value: gs://hettyversion-bak2gs
              - name: MYSQL_USER
                value: root
              - name: DUMP_DB
                value: hettyversion
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-user
                    key: password
              image: gcr.io/316443988803/bak2gs:b8da8e7-4
              name: bak2gs
              volumeMounts:
                - mountPath: /opt/gs/
                  name: creds
          restartPolicy: OnFailure
          volumes:
            - name: creds
              secret:
                secretName: bak2gs-creds
