version: '2'
services:
  db:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hettyversion
    ports:
      - 3306:3306
    volumes:
       - ./mysql-data:/var/lib/mysql
  app:
    build: .
    ports:
      - 5001:80
    links:
      - db
    environment:
      HETTYVERSION_MYSQL_IP: db
      USER_ENABLE_CONFIRM_EMAIL: 'False'
      USER_ENABLE_EMAIL: 'True'
