version: '2'
services:
  db:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hettyversion
    ports:
      - 3306:3306
  app:
    build: .
    ports:
      - 80:80
    links:
      - db
    environment:
      HETTYVERSION_MYSQL_IP: db
