"""empty message

Revision ID: 115eb65ac0d4
Revises: 69a1697c6218
Create Date: 2017-01-08 00:58:15.341021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115eb65ac0d4'
down_revision = '69a1697c6218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_song_band_id'), 'song', ['band_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_band_id'), table_name='song')
    # ### end Alembic commands ###
