"""empty message

Revision ID: 11f75f70fa80
Revises: ca0259276529
Create Date: 2017-01-04 20:03:21.627113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11f75f70fa80'
down_revision = 'ca0259276529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('band_id', sa.Integer(), nullable=True))
    op.add_column('song', sa.Column('song_id', sa.Integer(), nullable=False))
    op.drop_column('song', 'id')
    op.drop_column('song', 'bandid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('bandid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('song', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('song', 'song_id')
    op.drop_column('song', 'band_id')
    # ### end Alembic commands ###
