"""empty message

Revision ID: 127536b52f2d
Revises: 115eb65ac0d4
Create Date: 2017-01-12 17:19:35.208626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127536b52f2d'
down_revision = '115eb65ac0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('band', sa.Column('slug', sa.String(length=128), nullable=True))
    op.add_column('song', sa.Column('slug', sa.String(length=128), nullable=True))
    op.add_column('version', sa.Column('slug', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('version', 'slug')
    op.drop_column('song', 'slug')
    op.drop_column('band', 'slug')
    # ### end Alembic commands ###
