"""empty message

Revision ID: 2651411abfe8
Revises: 7609ef8e39cb
Create Date: 2017-01-17 21:23:38.784645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2651411abfe8'
down_revision = '7609ef8e39cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'show_id')
    op.drop_column('version', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('title', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('song', sa.Column('show_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
