"""empty message

Revision ID: 3e155e445470
Revises: acd9060445bb
Create Date: 2017-01-17 21:03:57.653487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e155e445470'
down_revision = 'acd9060445bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('phishin_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_foreign_key(None, 'song', 'band', ['band_id'], ['band_id'])
    op.create_foreign_key(None, 'user_roles', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'version', 'song', ['song_id'], ['song_id'])
    op.create_foreign_key(None, 'version_comment', 'user', ['author_id'], ['id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'version_comment', 'version', ['version_id'], ['version_id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'version_comment_vote', 'user', ['voter_id'], ['id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'version_comment_vote', 'version', ['version_id'], ['version_id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version_comment_vote', type_='foreignkey')
    op.drop_constraint(None, 'version_comment_vote', type_='foreignkey')
    op.drop_constraint(None, 'version_comment', type_='foreignkey')
    op.drop_constraint(None, 'version_comment', type_='foreignkey')
    op.drop_constraint(None, 'version', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_table('venue')
    # ### end Alembic commands ###
