"""empty message

Revision ID: 69a1697c6218
Revises: d85bc43e6546
Create Date: 2017-01-07 23:02:41.499290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a1697c6218'
down_revision = 'd85bc43e6546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('mu', sa.Float(), nullable=True))
    op.add_column('version', sa.Column('sigma', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('version', 'sigma')
    op.drop_column('version', 'mu')
    # ### end Alembic commands ###
