"""empty message

Revision ID: 7609ef8e39cb
Revises: ecd2483344eb
Create Date: 2017-01-17 21:14:06.556595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7609ef8e39cb'
down_revision = 'ecd2483344eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('song_ibfk_2', 'song', type_='foreignkey')
    op.drop_constraint('song_ibfk_1', 'song', type_='foreignkey')
    op.drop_constraint('version_ibfk_1', 'version', type_='foreignkey')
    op.drop_constraint('version_ibfk_2', 'version', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('version_ibfk_2', 'version', 'show', ['show_id'], ['show_id'])
    op.create_foreign_key('version_ibfk_1', 'version', 'song', ['song_id'], ['song_id'])
    op.create_foreign_key('song_ibfk_1', 'song', 'band', ['band_id'], ['band_id'])
    op.create_foreign_key('song_ibfk_2', 'song', 'show', ['show_id'], ['show_id'])
    # ### end Alembic commands ###
