"""empty message

Revision ID: a0548038a759
Revises: a392ca901b70
Create Date: 2017-01-19 19:39:02.344092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0548038a759'
down_revision = 'a392ca901b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listened_to',
    sa.Column('lt_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('lt_id')
    )
    op.create_foreign_key(None, 'user_roles', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'version_comment', 'version', ['version_id'], ['version_id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'version_comment', 'user', ['author_id'], ['id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'version_comment_vote', 'version', ['version_id'], ['version_id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'version_comment_vote', 'user', ['voter_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version_comment_vote', type_='foreignkey')
    op.drop_constraint(None, 'version_comment_vote', type_='foreignkey')
    op.drop_constraint(None, 'version_comment', type_='foreignkey')
    op.drop_constraint(None, 'version_comment', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_table('listened_to')
    # ### end Alembic commands ###
