"""empty message

Revision ID: acd9060445bb
Revises: 9e35cdfb69b5
Create Date: 2017-01-16 20:18:55.756201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd9060445bb'
down_revision = '9e35cdfb69b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('phishin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'song', 'band', ['band_id'], ['band_id'])
    op.create_foreign_key(None, 'user_roles', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('version', sa.Column('phishin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'version', 'song', ['song_id'], ['song_id'])
    op.create_foreign_key(None, 'version_comment', 'user', ['author_id'], ['id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'version_comment', 'version', ['version_id'], ['version_id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'version_comment_vote', 'version', ['version_id'], ['version_id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'version_comment_vote', 'user', ['voter_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version_comment_vote', type_='foreignkey')
    op.drop_constraint(None, 'version_comment_vote', type_='foreignkey')
    op.drop_constraint(None, 'version_comment', type_='foreignkey')
    op.drop_constraint(None, 'version_comment', type_='foreignkey')
    op.drop_constraint(None, 'version', type_='foreignkey')
    op.drop_column('version', 'phishin_id')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_column('song', 'phishin_id')
    # ### end Alembic commands ###
