"""empty message

Revision ID: ecd2483344eb
Revises: dbf78db824cd
Create Date: 2017-01-17 21:07:08.850408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd2483344eb'
down_revision = 'dbf78db824cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'song', 'show', ['show_id'], ['show_id'])
    op.add_column('version', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'version', 'show', ['show_id'], ['show_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version', type_='foreignkey')
    op.drop_column('version', 'show_id')
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_column('song', 'show_id')
    # ### end Alembic commands ###
