"""empty message

Revision ID: eeb12fbf394a
Revises: 11f75f70fa80
Create Date: 2017-01-04 20:04:09.739761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb12fbf394a'
down_revision = '11f75f70fa80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('lhs', sa.Integer(), nullable=True),
    sa.Column('rhs', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
